---
title: Blog Post 3
author: Kaela Ellis
date: '2022-09-26'
slug: []
categories: []
tags: []
---
```{r,  message = FALSE, echo=FALSE}
library(tidyverse)
library(stargazer)
# required packages 
require(tidyverse)
require(ggplot2)
require(sf)
require(blogdown)
require(stargazer)

popvote_df <- read.csv("~/Desktop/Gov1347/Gov-1347/Week 2/house_popvote_seats.csv") 
                                                   
# load GDP data by quarter
economy_df <- read.csv("~/Desktop/Gov1347/Gov-1347/Week 2/GDP_quarterly.csv")

#merge popvote_df and economy_df by year
dat <- left_join(economy_df, popvote_df, by = 'year')

# drop NAs (only election years)
dat <- dat %>%
  drop_na()

# new df
dat2 <- dat %>% 
    select('year', 'winner_party', 'H_incumbent_party', 'H_incumbent_party_majorvote_pct', 
           'quarter_cycle', 'GDP_growth_pct', 'R_majorvote_pct') %>%
    filter(quarter_cycle == 7)  

dat2.no2020 <- dat2 [-c(1, 2, 3), ]

#using the consumer sentiment of the last recorded consumer sentiment prior to Novemeber, starting in the year 1954 for economic data
dat2.no2020$consumer.sentiment <- c(82.9, 99.9, 80.9, 97.2, 95.4, 100.6, 91.2, 92.4, 77.6, 95.2, 93.7, 89.7, 79.3, 75, 73.4, 96.3, 95.6, 94.1, 63.9, 73.3, 92.7, 96.5, 97.4, 105.8, 80.6, 91.7, 93.6, 57.6, 67.7, 82.6, 86.9, 87.2, 98.6, 81.8)
```

```{r, message = FALSE, echo=FALSE}
#post 1992 only
dat2.no2020 <- dat2 [-c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22), ]

dat2.no2020$consumer.sentiment.old <- c(73.3, 92.7, 96.5, 97.4, 105.8, 80.6, 91.7, 93.6, 57.6, 67.7, 82.6, 86.9, 87.2, 98.6, 81.8)

#subtracting October from September 
dat2.no2020$consumer.sentiment <-c((73.3-75.6), (92.7-91.5), (96.5-94.7), (97.4-100.9), (105.8-106.80), (80.6-86.10), (91.7-94.20), (93.6-85.40), (57.6-70.30), (67.7-68.20), (82.6-78.30), (86.9-84.60), (87.2-91.20), (98.6-100.10), (81.8-80.40))

dat2.no2020 %>%
  ggplot(aes(x=consumer.sentiment, y=R_majorvote_pct,
             label=year)) + 
    geom_text(size = 4) +
    geom_smooth(method="lm", formula = y ~ x) +
    geom_hline(yintercept=50, lty=2) +
    geom_vline(xintercept=0.01, lty=2) + # median
    xlab("Consumer Sentiment") +
    ylab("Incumbent party PV") +
    theme_bw()  +
    ggtitle("Figure 1: Effect of Consumer Sentiment on Incumbent Party Popular Vote Share") +
  theme(axis.text = element_text(size = 12),
          axis.title = element_text(size = 12),
          plot.title = element_text(size = 12)) 
```

```{r, message = FALSE, echo=FALSE}

#use data from 7th quarter which occurs 7/1 -10/1

popvote_df <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 2/house_popvote_seats.csv") 
                                                   
# load GDP data by quarter
economy_df <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 2/GDP_quarterly.csv")

#merge popvote_df and economy_df by year
dat <- left_join(economy_df, popvote_df, by = 'year')

# drop NAs (only election years)
dat <- dat %>%
  drop_na()

# new df
dat2 <- dat %>% 
    select('year', 'winner_party', 'H_incumbent_party', 'H_incumbent_party_majorvote_pct', 
           'quarter_cycle', 'GDP_growth_pct', "R_majorvote_pct") %>%
    filter(quarter_cycle == 7)  
dat2.no202 <- dat2 [-c(1, 37), ]
lm_econ <- lm(R_majorvote_pct ~ GDP_growth_pct, 
              data = dat2.no202)
```

```{r, message = FALSE, echo=FALSE}
#polls pls
polldata <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 3/GenericPolls1942_2020.csv")

polldata$DUE.weight <- (365 - polldata$days_until_election)

poll <- polldata %>% 
  group_by(year) %>% 
  filter(DUE.weight > 0)

poll <- poll %>%
  drop_na()
 
all <- full_join(dat2.no2020, poll, by = "year")


all$rep.2.party.poll <- (all$rep)/ (all$rep + all$dem) *100


lm_Gpolls <- lm(R_majorvote_pct ~ rep.2.party.poll, data = all)

lm_all <- lm(R_majorvote_pct ~ rep.2.party.poll  + consumer.sentiment, data = all)


```

```{r, message = FALSE, echo=FALSE}
data.2022 <- read.csv("~/Desktop/Gov1347/Gov-1347/Week 3/generic_ballot_polls.csv")
data.2022 <- data.2022 %>% 
  rename(year = cycle)

data.2022$rep.2.party.poll <- (data.2022$rep)/ (data.2022$rep + data.2022$dem) *100
data.2022$consumer.sentiment <- 59.50-58.20



model <- predict(lm_all, data.2022, interval="prediction")
mean(model)

lm_CS <- lm(R_majorvote_pct ~ consumer.sentiment, data = dat2.no2020)
```

```{r, message = FALSE, echo=FALSE}
#more code
plot(all$year, all$R_majorvote_pct, 
     type="l",
     main="True vs Predicted Vote Share",
     xlab = "Year",
     ylab = "Republican Vote Share")
lines(all$year, predict(lm_CS, all), col = "darkgreen", lty = 3)
lines(all$year, predict(lm_Gpolls, all), col = "pink", lty = 3)
lines(all$year, predict(lm_econ, all), col = "blue", lty = 3)
lines(all$year, predict(lm_all, all), col = "purple", lty = 3)
legend("bottomleft", c("Actual VS", "Consumer Sentiment Only", "Generic Polls Only", "GDP Only", "Polls + CS"),
       lty = c(1, 3),
       col = c("black", "darkgreen", "pink", "blue", "purple"))
```

```{r, message = FALSE, echo=FALSE}
stargazer(lm_CS, lm_Gpolls, lm_econ,lm_all, title = "Results", type = "text", column.labels = c("CS","Gpolls", "GDP", "Gpolls + CS"), covariate.labels = c("Consumer Sentiment", "Generic Polls", "GDP", "Generic Polls + Consumer Sentiment"))

```

