---
title: Blog_Post_6
author: Kaela Ellis
date: '2022-10-20'
slug: []
categories: []
tags: []
---

```{r}
library(tidyverse)
library(janitor)
library(glmnet)
library(sf)
library(plotly)
library(usmap)
library(rmapshaper)
library(blogdown)
library(gridExtra)
library(stargazer)
library(lubridate)
#library(caret)
library(leaps)
library(ggthemes)
#library(usdata)
#library(gt)
#library(gtsummary)
library(cowplot)

```

```{r}
incumb <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 4/incumb_dist_1948-2022 (2).csv")


incumb <- incumb %>%  mutate(incumb = ifelse(winner_candidate == "DemCandidate",1,0))%>% filter(year > 2008) %>% select(year, st_cd_fips, incumb, winner_candidate, state, district_num) %>% mutate(year = year +2) %>% select (year, st_cd_fips, incumb, state, district_num)

```

```{r}
turnout <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/turnout.csv")
output <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/preds_df.csv")

turnout2 <- turnout %>% rename("DISTRICT" = "district_num") %>% rename("STATENAME" = "state") %>% rename("state_dists" = "st_cd_fips") %>% filter(year == 2020) %>% select(state_dists, DISTRICT, STATENAME)

output <- output %>% left_join(turnout2, by=c("state_dists"))

get_congress_map <- function(cong=114) {
  tmp_file <- tempfile()
  tmp_dir  <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts114.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts114.shp",cong), sep = "/")
  st_read(fpath)
}

cd114 <- get_congress_map(114)

cd114$DISTRICT <- as.numeric(cd114$DISTRICT)
cd114 <- cd114 %>% left_join(dem_results, by=c("DISTRICT", "STATENAME"))

output <- output %>% 
  mutate(preds = ifelse(preds > 100,100, preds),
         preds = ifelse(preds < 0, 0, preds))

```

```{r}
cd114$DISTRICT <- as.numeric(cd114$DISTRICT)
output$DISTRICT <- as.numeric(output$DISTRICT)
cd114$DISTRICT <- as.numeric(cd114$DISTRICT)
output$STATENAME <- as.character(output$STATENAME)
cd114$STATENAME <- as.character(cd114$STATENAME)

cd2022 <- cd114 %>% left_join(output, by=c("STATENAME", "DISTRICT")) %>% filter(!STATENAME %in% c("Alaska","Hawaii"))
cd2022%>% st_as_sf() %>%
  st_transform("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +ellps=sphere +units=m +no_defs")
districts_simp_2022 <- rmapshaper::ms_simplify(cd2022, keep = 0.01)
fig1 <- ggplot() + 
  geom_sf(data=districts_simp_2022,aes(fill=preds),
          inherit.aes=FALSE,alpha=0.9) + 
  scale_fill_gradient2("Democratic \nVoteshare", midpoint = 50, high = "#30a2da", mid = "white", low = "#fc4f30") +
  #coord_sf(xlim = c(-124.43, -66.57), ylim = c(23, 49), expand = FALSE) +  
  theme_void() + labs(title = "2022 Prediction with Turnout") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

#Insert no turnout dataset here
no_TO <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/better_preds.csv")
no_TO <- no_TO %>% left_join(turnout2, by=c("state_dists"))

no_TO <- no_TO %>%  mutate(preds = ifelse(preds > 100,100, preds),
         preds = ifelse(preds < 0, 0, preds))

cd114$DISTRICT <- as.numeric(cd114$DISTRICT)
no_TO$DISTRICT <- as.numeric(no_TO$DISTRICT)
cd114$DISTRICT <- as.numeric(cd114$DISTRICT)
no_TO$STATENAME <- as.character(no_TO$STATENAME)
cd114$STATENAME <- as.character(cd114$STATENAME)

cd2022_no_TO <- cd114 %>% left_join(no_TO, by=c("STATENAME", "DISTRICT")) %>% filter(!STATENAME %in% c("Alaska","Hawaii"))
cd2022_no_TO%>% st_as_sf() %>%
  st_transform("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +ellps=sphere +units=m +no_defs")
districts_simp_2022_no_TO <- rmapshaper::ms_simplify(cd2022_no_TO, keep = 0.01)
fig2 <- ggplot() + 
  geom_sf(data=districts_simp_2022_no_TO,aes(fill=preds),
          inherit.aes=FALSE,alpha=0.9) + 
  scale_fill_gradient2("Democratic \nVoteshare", midpoint = 50, high = "#30a2da", mid = "white", low = "#fc4f30") +
  #coord_sf(xlim = c(-124.43, -66.57), ylim = c(23, 49), expand = FALSE) +  
  theme_void() + labs(title = "2022 Prediction without Turnout") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
fig1

plot_grid(fig1, fig2, ncol=2)

fig2

comparison <- no_TO %>%  left_join(output, by=c("STATENAME", "DISTRICT")) %>% filter(!STATENAME %in% c("Alaska","Hawaii"))

comparison$preds.x <- as.numeric(comparison$preds.x)

comparison1 <- comparison %>% mutate(preds.x = ifelse(preds.x > 50,1,0)) %>% mutate(preds.y = ifelse(preds.y > 50,1,0))

comparison1$pred.diff <- comparison1$preds.x - comparison1$preds.y

cdcomp <- cd114 %>% left_join(comparison1, by=c("STATENAME", "DISTRICT")) %>% filter(!STATENAME %in% c("Alaska","Hawaii"))
cdcomp%>% st_as_sf() %>%
  st_transform("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +ellps=sphere +units=m +no_defs")
districts_simp_comp <- rmapshaper::ms_simplify(cdcomp, keep = 0.01)
ggplot() + 
  geom_sf(data=districts_simp_comp,aes(fill=pred.diff),
          inherit.aes=FALSE,alpha=0.9) + 
  scale_fill_gradient2("Flipped \n States", midpoint = 0, high = "#30a2da", mid = "white", low = "#fc4f30") +
  #coord_sf(xlim = c(-124.43, -66.57), ylim = c(23, 49), expand = FALSE) +  
  theme_void() + labs(title = "States that Flipped turnout vs without turnout") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
#comparison1 %>%
 # filter(preds.x == 0)
```

```{r}
#Seats that flipped 2020 to 2022
#results from 2020 compared to results from 2022
no_TO <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/better_preds.csv")
turnout2 <- turnout %>% rename("DISTRICT" = "district_num") %>% rename("STATENAME" = "state") %>% rename("state_dists" = "st_cd_fips") %>% filter(year == 2020) %>% select(state_dists, DISTRICT, STATENAME)

no_TO <- no_TO %>% left_join(turnout2, by=c("state_dists"))
historical_results <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 4/house party vote share by district 1948-2020.csv") %>% 
  clean_names()
dem_results_2020 <- historical_results %>% 
  select(race_year, state, area, dem_votes_major_percent, district_num) %>% 
  rename("year" = "race_year") %>%  rename("DISTRICT" = "district_num") %>% rename("STATENAME" = "state") %>% filter(year == 2020) %>% distinct() %>% distinct(STATENAME,DISTRICT, .keep_all = TRUE)

dem_results_2020$DISTRICT <- as.numeric(dem_results_2020$DISTRICT)
no_TO$DISTRICT <- as.numeric(no_TO$DISTRICT)
dem_results_2020$DISTRICT <- as.numeric(dem_results_2020$DISTRICT)
no_TO$STATENAME <- as.character(no_TO$STATENAME)
dem_results_2020$STATENAME <- as.character(dem_results_2020$STATENAME)
diff.2020.2022 <- no_TO %>% left_join(dem_results_2020, by=c("STATENAME", "DISTRICT"))

diff.2020.2022 <- diff.2020.2022 %>%  mutate(preds = ifelse(preds > 50,1,0)) %>% mutate(dem_votes_major_percent = ifelse(dem_votes_major_percent > 50,1,0))
diff.2020.2022 <- as.data.frame(diff.2020.2022)
diff.2020.2022$pred.diff <- diff.2020.2022$preds - diff.2020.2022$dem_votes_major_percent

cd114$DISTRICT <- as.numeric(cd114$DISTRICT)
diff.2020.2022$DISTRICT <- as.numeric(diff.2020.2022$DISTRICT)
cd114$DISTRICT <- as.numeric(cd114$DISTRICT)
diff.2020.2022$STATENAME <- as.character(diff.2020.2022$STATENAME)
cd114$STATENAME <- as.character(cd114$STATENAME)

diff.2020.2022 <- cd114 %>% left_join(diff.2020.2022, by=c("STATENAME", "DISTRICT")) %>% filter(!STATENAME %in% c("Alaska","Hawaii"))
diff.2020.2022%>% st_as_sf() %>%
  st_transform("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +ellps=sphere +units=m +no_defs")
districts_simp_2022_comb <- rmapshaper::ms_simplify(diff.2020.2022, keep = 0.01)
ggplot() + 
  geom_sf(data=districts_simp_2022_comb,aes(fill=pred.diff),
          inherit.aes=FALSE,alpha=0.9) + 
  scale_fill_gradient2("Democratic \nVoteshare", midpoint = 0, high = "#30a2da", mid = "white", low = "#fc4f30") +
  #coord_sf(xlim = c(-124.43, -66.57), ylim = c(23, 49), expand = FALSE) +  
  theme_void() + labs(title = "Seats flipped 2020 to 2022: Without Turnout") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

```

```{r}
#as.data.frame(diff.2020.2022 %>%
 # filter(pred.diff != 0)) %>%  mutate(diff.2020.2022 = ifelse(pred.diff == -1,"R",pred.diff), diff.2020.2022 = ifelse(pred.diff == 1,"D",diff.2020.2022)) %>% select(STATENAME, DISTRICT,  diff.2020.2022)
```

```{r}
average <- c(221, 214)
high <- c(224, 211)
low<- c(215, 220)

df <- as.data.frame(rbind(average, high, low))
df <- df %>% rename("Republican" = "V1") %>%  rename("Democrat" = "V2")
df

ggplot(df, aes(x = Democrat, y = c(average, high, low), fill = Democrat)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("#30a2da", "#fc4f30")) +
  ylab("Seats") + xlab("Voter Turnout") +
  # ggtitle("Incumbency win rate by year") +
  coord_flip() + 
  theme_bw() + 
  theme(axis.title = element_text(size=10),
        axis.text = element_text(size=5),
        strip.text.y = element_text(size = 5))

df <- df %>%
  group_by(year) %>% mutate(tot_n=n()) %>% ungroup() %>%
  ## this one is get numerator and calculate % by party
  group_by(year, winner_candidate_inc) %>% summarise(p_n=n()*100/first(tot_n)) %>% ungroup() %>%
   ## filter idiosyncratic issues
  filter(p_n != 100.000000) %>%
  ## finally, this one so we can sort the issue names
  ## by D% of issue ad-share instead of alphabetically
  group_by(year) %>% mutate(Dp_n = ifelse(first(winner_candidate_inc) == "democrat", first(p_n), 0))

ggplot(incumb_ed, aes(x = reorder(year, Dp_n), y = p_n, fill = winner_candidate_inc)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("darkgreen", "purple1")) +
  ylab("Incumbency Win Rate") + xlab("Year") +
  # ggtitle("Incumbency win rate by year") +
  coord_flip() + 
  theme_bw() + 
  theme(axis.title = element_text(size=10),
        axis.text = element_text(size=5),
        strip.text.y = element_text(size = 5)) 
```

```{r}
cvap <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/cvap_district_2012-2020_clean.csv")
electionresults <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/incumb_dist_1948-2020 (3).csv")
genericballot <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 3/polls_df.csv")
gdp_q <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 2/GDP_quarterly.csv")
incumbency <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/incumb.csv")
```
```{r}
# renaming geoid to st_cd_fips for left join
cvap <- cvap %>% 
  rename(st_cd_fips = geoid) 

# create turnout dataframe by left joining election results and cvap
turnout <-left_join(electionresults, cvap, by = c("year", "st_cd_fips")) %>% 
  select(year, state.x, district_num, winner_party, 
         RepVotes, DemVotes, DemVotesMajorPercent, st_cd_fips, cvap) %>% 
  filter(year >= 2012) %>%  # filter for 2012-2020
  rename(state = state.x) %>% 
  mutate(turnout = (RepVotes + DemVotes) / cvap * 100) # turnout column

# creating polls_d dataframe by cleaning genericballots
genericballot$poll_date <- as.Date(genericballot$poll_date, format = "%m/%d/%Y")

cleaned_polls <- genericballot %>% 
  filter(year >= 2012,
         days_until_election <= 52) %>% 
         # the closest poll to election day for 1952 was 51.5
  group_by(year, party) %>% 
  summarise(average_support = mean(support))

polls_d <- cleaned_polls %>% 
  filter(party =="D")

# adding generic ballot average to turnout
turnout <- left_join(turnout, polls_d, by = "year") %>% 
  select(year, state, district_num, winner_party, RepVotes, DemVotes,
         DemVotesMajorPercent, st_cd_fips, cvap, turnout, average_support)
```

```{r adding economy and incumbency}
# Create quarter change data and join all together with popular vote

# Filter out data for Q6
gdp_q6 <- gdp_q %>%
  filter(year >= 2012, 
         quarter_cycle == 6) %>% 
  rename(gdp_q6 = GDPC1)

# Filter out data for Q7
gdp_q7 <- gdp_q %>%
  filter(year >= 2012, 
         quarter_cycle == 7) %>% 
  rename(gdp_q7 = GDPC1)

# creating gdp_q_final
gdp_q_final <- left_join(gdp_q7, gdp_q6, by = "year") %>% 
  mutate(gdp_q7_q6 = (gdp_q7 - gdp_q6) / gdp_q6 * 100) %>% # percent difference
  rename(gdp_percent_difference = gdp_q7_q6) %>% 
  select(year, gdp_percent_difference)

# merging gdp_q_final and turnout
turnout <- left_join(turnout, gdp_q_final, by = "year")

# merging incumbency and turnout
turnout <- left_join(turnout, incumbency, by = c("year", "st_cd_fips")) %>% 
  select(year, state, district_num, winner_party, RepVotes, DemVotes,
         DemVotesMajorPercent, st_cd_fips, cvap, turnout, 
         average_support, gdp_percent_difference, incumb)
```

```{r}
# creating 2022 dataframe
# first, add the average voter turnout in district from 2012-2020
turnout_2022 <- turnout %>% 
  group_by(st_cd_fips) %>% 
  mutate(historical_turnout_by_district = mean(turnout)) %>% 
  ungroup() %>% 
  select(year, state, district_num, st_cd_fips, historical_turnout_by_district) %>% 
  filter(year == 2012) %>% 
  select(-year)

# second, add nationwide variables
# Generic ballot: 45.6% for Democrats from FiveThirtyEight
# GDP: -0.6 (taken from Q2 change)
turnout_2022 <- turnout_2022 %>% 
  mutate(average_support = 45.6,
         gdp_percent_difference = -0.6)

# Incumbency
incumbency_2022 <- incumbency %>% 
  filter(year == 2022)

# Final 2022 data set to predict on
turnout_2022 <- left_join(turnout_2022, incumbency_2022, by = "st_cd_fips") %>% 
  select(state, district_num, st_cd_fips, historical_turnout_by_district,
         average_support, gdp_percent_difference, incumb) %>% 
  unique()

write.csv(turnout_2022, "turnout_2022.csv")
``` 

```{r}
models <- list()
r2 <- c()
preds <- c()

state_dists <- unique(turnout$st_cd_fips)

for (sd in state_dists){
  # Filter for dataframe with just district sd
  temp <- turnout %>%
    filter(st_cd_fips == sd)
  
  # Fit linear model for dem two-party vote-share
  m <- lm(turnout ~ year, data = temp)
  
  # Add model to list of models
  models[[length(models)+1]] <- m
  
  # Find r^2 and add to list of r^squareds
  r2 <- c(r2, summary(m)$adj.r.squared)
  
  new_data <- data.frame(year = 2022)
  
  preds <- c(preds, predict(m, new_data))
}

# create a column with the new turnout
turnout_2022$new_turnout=preds

```

```{r}

turnout <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/turnout_2012_2020.csv")
turnout22 <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/turnout_2022.csv")
electionresults <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 6/incumb_dist_1948-2020 (3).csv")
genericballot <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 3/polls_df.csv")
gdp_q <- read_csv("~/Desktop/Gov1347/Gov-1347/Week 2/GDP_quarterly.csv")

```

```{r}
genericballot <- genericballot %>% 
  mutate(poll_data = as.Date(genericballot$poll_date, format = "%m/%d/%Y")) %>%
  filter(days_until_election <= 52) %>% 
         # the closest poll to election day for 1952 was 51.5
  group_by(year, party) %>% 
  summarise(average_support = mean(support)) %>%
  filter(party =="D")

# Filter out data for Q6
gdp_q6 <- gdp_q %>%
  filter(quarter_cycle == 6) %>% 
  rename(gdp_q6 = GDPC1)

# Filter out data for Q7
gdp_q7 <- gdp_q %>%
  filter(quarter_cycle == 7) %>% 
  rename(gdp_q7 = GDPC1)

# creating gdp_q_final
gdp_q_final <- left_join(gdp_q7, gdp_q6, by = "year") %>% 
  mutate(gdp_q7_q6 = (gdp_q7 - gdp_q6) / gdp_q6 * 100) %>% # percent difference
  rename(gdp_percent_difference = gdp_q7_q6) %>% 
  select(year, gdp_percent_difference)

incumbency <- electionresults %>%  
  mutate(incumb = ifelse(winner_candidate == "DemCandidate",1,0)) %>% 
  mutate(year = year + 2) %>% 
  select (year, st_cd_fips, incumb)


# adding generic ballot average to turnout
df <- left_join(electionresults, genericballot, by = "year") %>%
  left_join(gdp_q_final, by = "year") %>%
  left_join(incumbency, by = c("year", "st_cd_fips")) %>% 
  select(year, state, district_num, winner_party, RepVotes, DemVotes,
         DemVotesMajorPercent, st_cd_fips,
         average_support, gdp_percent_difference, incumb) %>%
  drop_na(incumb)

state_dists <- unique(turnout$st_cd_fips)
```

```{r}
turnout14 <- turnout %>%
  filter(year == 2014) %>%
  select(year, turnout, st_cd_fips) %>%
  distinct() %>%
  distinct(st_cd_fips, .keep_all = TRUE)
turnout18 <- turnout %>%
  filter(year == 2018) %>%
  select(year, turnout, st_cd_fips) %>%
  distinct() %>%
  distinct(st_cd_fips, .keep_all = TRUE)
turnout22_fixed <- left_join(turnout14, turnout18, by = "st_cd_fips") %>%
  mutate(hist_avg = (turnout.x + turnout.y)/2) %>%
  select(st_cd_fips, hist_avg)
turnout22 <- left_join(turnout22, turnout22_fixed, by = "st_cd_fips") %>%
  select(historical_turnout_by_district)
```


# Model with Turnout

```{r, warning = FALSE}
# Instantiate lists
models <- list()
r2 <- c()
preds <- c()
preds_high <- c()
preds_low <- c()
coeff_support <- c()
coeff_turnout <- c()
coeff_gdp <- c()
coeff_incumb <- c()

# Loop through each district, model and predict
for (sd in state_dists){
  # Filter for dataframe with just district sd
  temp <- turnout %>%
    filter(st_cd_fips == sd)
  
  # Fit linear model for dem two-party vote-share
  m <- lm(DemVotesMajorPercent ~ average_support + turnout + gdp_percent_difference + incumb, data = temp)
  
  # Add model to list of models
  models[[length(models)+1]] <- m
  
  # Find r^2, coeffs, and add to list
  r2 <- c(r2, summary(m)$adj.r.squared)
  coeff_support <- c(coeff_support, summary(m)$coefficients[2])
  coeff_turnout <- c(coeff_turnout, summary(m)$coefficients[3])
  coeff_gdp <- c(coeff_gdp, summary(m)$coefficients[4])
  coeff_incumb <- c(coeff_incumb, summary(m)$coefficients[5])
  
  # Make a 2022 prediction and append to list
  new_data <- turnout22 %>%
    filter(st_cd_fips == sd) %>%
    rename(turnout = hist_avg)
  preds <- c(preds, predict(m, new_data))
  preds_high <- c(preds_high, predict(m, new_data %>% mutate(turnout = turnout + 8)))
  preds_low <- c(preds_low, predict(m, new_data %>% mutate(turnout = turnout - 8)))
}

output <- tibble(state_dists, preds, preds_high, preds_low, r2, coeff_gdp, coeff_incumb, coeff_support, coeff_turnout)
```

```{r}
state_dists[435]
```

```{r}
stargazer(m, type = "text")
```


```{r}
tbl_regression(m)
```



```{r}
preds_df <- tibble(state_dists, preds, preds_high, preds_low)
#write.csv(preds_df, "preds_df.csv")
```


```{r}
length(preds[preds <= 50])
length(preds[preds > 50])
```

```{r}
length(preds[preds_high <= 50])
length(preds[preds_high > 50])
```

```{r}
length(preds[preds_low <= 50])
length(preds[preds_low > 50])
```

```{r}
ggplot(turnout %>% filter(year == 2018), aes(x = DemVotesMajorPercent)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "Actual 2018 House Election Results",
       subtitle = "House Districts",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  ylim(0,50)
```

```{r}
ggplot(output %>% mutate(preds = ifelse(preds > 100, 100, preds),
                                        preds = ifelse(preds < 0, 0, preds)), 
       aes(x = preds)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "2022 Election Predictions - Turnout Model",
       subtitle = "Average Turnout",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  xlim(-5, 105) +
  ylim(0,50)

ggplot(output %>% mutate(preds_high = ifelse(preds_high > 100, 100, preds_high),
                                        preds_high = ifelse(preds_high < 0, 0, preds_high)), 
       aes(x = preds_high)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "2022 Election Predictions - Turnout Model",
       subtitle = "High Turnout",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  xlim(-5, 105) +
  ylim(0,50)

ggplot(output %>% mutate(preds_low = ifelse(preds_low > 100, 100, preds_low),
                                        preds_low = ifelse(preds_low < 0, 0, preds_low)), 
       aes(x = preds_low)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "2022 Election Predictions - Turnout Model",
       subtitle = "Low Turnout",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  xlim(-5, 105) +
  ylim(0,50)
```

```{r}
output_stacked <- output %>% 
  pivot_longer(cols = c(preds, preds_high, preds_low), names_to = "preds") %>%
  mutate(value = ifelse(value > 100, 100, value), 
         value = ifelse(value < 0, 0, value))

ggplot(output_stacked, aes(x=value, fill=preds)) +
  geom_histogram(alpha=0.2, position='identity')
```



```{r}
ggplot(output, aes(x = r2)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "R-Squared Values for Turnout Models in Each District",
       subtitle = "House Districts",
       x = "R-Squared",
       y = "Count")
```

```{r}
p1 <- ggplot(output, aes(x = coeff_gdp)) +
  geom_histogram(bins = 30) + 
  theme_few() +
  labs(x = "GDP Coefficient",
       y = "Count")
p2 <- ggplot(output, aes(x = coeff_support)) +
  geom_histogram(bins = 30) +
  theme_few() +
  labs(x = "Generic Ballot Coefficient",
       y = "Count")
p3 <- ggplot(output, aes(x = coeff_turnout)) +
  geom_histogram(bins = 30) + 
  theme_few() +
  labs(x = "Turnout Coefficient",
       y = "Count")
grid.arrange(p1, p2, p3)
```

```{r}
p1 <- ggplot(output, aes(x = coeff_gdp)) +
  geom_histogram(bins = 30, color = "white") + xlim(-2.5, 2.5) + 
  geom_vline(xintercept = median(output$coeff_gdp, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "GDP Coefficient",
       y = "Count") +
  ylim(0, 130)

p2 <- ggplot(output, aes(x = coeff_support)) +
  geom_histogram(bins = 30, color = "white") + xlim(-10, 10) +  
  geom_vline(xintercept = median(output$coeff_support, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Generic Ballot Coefficient",
       y = "Count") +
  ylim(0, 130)

p3 <- ggplot(output, aes(x = coeff_turnout)) +
  geom_histogram(bins = 30, color = "white") + xlim(-2.5, 2.5) + 
  geom_vline(xintercept = median(output$coeff_turnout, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Turnout Coefficient",
       y = "Count") +
  ylim(0, 130)

p4 <- ggplot(output, aes(x = coeff_incumb)) +
  geom_histogram(bins = 30, color = "white") + xlim(-20, 20) + 
  geom_vline(xintercept = median(output$coeff_incumb, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Incumbency Coefficient",
       y = "Count") +
  ylim(0, 130)

grid.arrange(p1, p2)
```

```{r}
p3
```


# Models v2

```{r, warning = FALSE}
models <- list()
r2 <- c()
preds <- c()
coeff_support <- c()
coeff_gdp <- c()
coeff_incumb <- c()
for (sd in state_dists){
  # Filter for dataframe with just district sd
  temp <- df %>%
    filter(year != 2022) %>%
    filter(st_cd_fips == sd)
  
  # Fit linear model for dem two-party vote-share
  m <- lm(DemVotesMajorPercent ~ average_support + gdp_percent_difference + incumb, data = temp)
  
  # Add model to list of models
  models[[length(models)+1]] <- m
  
  # Find r^2, coeffs, and add to list
  r2 <- c(r2, summary(m)$adj.r.squared)
  coeff_support <- c(coeff_support, summary(m)$coefficients[2])
  coeff_gdp <- c(coeff_gdp, summary(m)$coefficients[3])
  coeff_incumb <- c(coeff_incumb, summary(m)$coefficients[4])
  
  # Make a 2022 prediction and append to list
  new_data <- turnout22 %>%
    filter(st_cd_fips == sd) %>%
    rename(turnout = hist_avg)
  preds <- c(preds, predict(m, new_data))
}
```

```{r}
stargazer(m, type = "text")
```


```{r}
better_preds <- tibble(state_dists, preds)
output_v2 <- tibble(r2, preds, coeff_support, coeff_gdp, coeff_incumb)
#write.csv(better_preds, "better_preds.csv")
```

```{r}
ggplot(output_v2, aes(x = r2)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "R-Squared Values for Models w/o Turnout in Each District",
       subtitle = "House Districts",
       x = "R-Squared",
       y = "Count")
```

```{r}
ggplot(output_v2 %>% mutate(preds = ifelse(preds > 100, 100, preds),
                                        preds = ifelse(preds < 0, 0, preds)), 
       aes(x = preds)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "2022 Election Predictions - Model w/o Turnout",
       subtitle = "House Districts",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  xlim(-5, 105) +
  ylim(0,50)
```

```{r}
p1 <- ggplot(output_v2, aes(x = coeff_gdp)) +
  geom_histogram(bins = 30, color = "white")
  geom_vline(xintercept = median(output_v2$coeff_gdp, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "GDP Coefficient",
       y = "Count") +
  ylim(0, 150)

p2 <- ggplot(output_v2, aes(x = coeff_support)) +
  geom_histogram(bins = 30, color = "white")
  geom_vline(xintercept = median(output_v2$coeff_support, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Generic Ballot Coefficient",
       y = "Count") +
  ylim(0, 150)

p3 <- ggplot(output_v2, aes(x = coeff_incumb)) +
  geom_histogram(bins = 30, color = "white") 
  geom_vline(xintercept = median(output_v2$coeff_incumb, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Incumbency Coefficient",
       y = "Count") +
  ylim(0, 150)

grid.arrange(p1, p2, p3)
```

```{r}
p3
```


```{r}
summary(m)
```






