---
title: Blog_Post_6
author: Kaela Ellis
date: '2022-10-20'
slug: []
categories: []
tags: []
---



<p>Welcome to my 2022 Midterm blog series. I’m Kaela Ellis, a junior at Harvard College studying Government. This semester I am taking Gov 1347: Election Analytics taught by Professor Ryan Enos, which has led to the creation of this blog. I will use this blog series to predict the 2022 Midterm election. The series will be updated weekly with new predictive measures and analyses of past elections.</p>
<p>This week I decided to incorporate turnout, incumbency, and expert predictions into my district-level two-party vote share prediction. As we saw from previous weeks campaigns do three things: persuade voters to support their candidate, turnout voters to support their vote, and convince voters to donate. Campaigns are not very effective in persuading voters to support their candidate. They have greater efficacy when trying to increase voter turnout. For example, as the Enos and Fowler reading found, the Obama campaign in 2012 increased voter turnout by approximately 8 percentage points, showing that campaigns have the potential to increase turnout by 8 points.</p>
<p>However, some of the readings from this week also explored the drawbacks of ground game efforts. For example Enos and Hersh point out that canvassers are more ideologically extreme and have different policy priorities than the median voter. They point out that canvassers are likely so ideologically extreme because citizens who have ideological extremes gain more utility in pushing their extreme positions. Additionally, partaking in political activism can make one more polarized. Enos and Hersh found that 73% of the mass public thought that the economy was the most important issue, while less than 40% of canvassers thought so. This demonstrates how canvassers have different policy priorities. This leads to a principal-agent problem, as candidates have limited control over volunteer canvassers. As a result of factors such as these, Enos and Hersh found that voters contacted by in-person Obama canvassers were less likely to support Obama, demonstrating a backfire effect.</p>
<p>This week I used voter turnout as a proxy for turnout. I worked on some of the code for this blog post with Lucy Ding and Jude Park. We created a district-by-district forecast, including the variables: average support, turnout, GDP, and incumbency. I used these variable in the model as follows:</p>
<p>I calculated district level turnout by adding the Republican vote share and adding it to the Democratic vote share, and then dividing it by the current voting age population (CVAP). While this is not necessarily the best way to predict turnout, we have the most readily available data on this. The main drawback to using this I found was that I could only find data on turnout tracking back to 2012. This is clearly very limited, as it only gives me 5 points of data to predict my forecast off of. With less points of data, the accuracy of my forecast is limited. Other methods for calculating turnout that would be more reflective of ground game efforts would be a measure of some of the factors that Gerber and Green discussed in their 2015 paper. They discussed how get out the vote efforts that emphasized one’s civic duty, polling place location, and reminder of an early pledge to vote are statistically proven to increase voter turnout. Meanwhile other GOTV efforts, such as leaflets, signage, direct mail reminders, and emails, have no apparent effect. A measure of the effective GOTV methods may inform how campaign efforts can effect election turnout more accurately. However, this data is not accessible, and therefore I defaulted to using the CVAP.</p>
<p>To calculate average support, I averaged the generic ballot for 52 days prior to the election. I have discussed this decision in earlier blog iterations in greater detail. I may pivot to using a different metric in my final calculation, but the general thought here was that generic ballots closer to the election are more accurate and, therefore, better predictors of the election results.</p>
<p>To calculate the economic factor, I used quarter 6 to 7 difference for GDP. Again, I have discussed different metrics for determining the economic effect. This is not the best economic factor, and I may pivot in my final calculation, but my thought here was that the change in GDP from Q6 to Q7 is the most recent, and, therefore, the most salient.</p>
<p>For incumbency, I calculated whether or not the Democratic party was the incumbent. I have discussed this decision in past blog iterations, but the general thought here was that there is an incumbency advantage, and to calculate its affect on the Democratic vote share I code for incumbency in a 0:1 form.</p>
<pre><code>## Reading layer `districts114&#39; from data source 
##   `/private/var/folders/53/y4tjcyz17pq_kfwb17bygwvm0000gp/T/RtmpCAhRra/districtShapes/districts114.shp&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 436 features and 15 fields (with 1 geometry empty)
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -179.1473 ymin: 18.91383 xmax: 179.7785 ymax: 71.35256
## Geodetic CRS:  NAD83</code></pre>
<pre><code>## Simple feature collection with 435 features and 23 fields (with 1 geometry empty)
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -2031905 ymin: -2116976 xmax: 2516388 ymax: 732376
## CRS:           +proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +ellps=sphere +units=m +no_defs
## First 10 features:
##    STATENAME           ID DISTRICT STARTCONG ENDCONG DISTRICTSI COUNTY PAGE
## 1  Louisiana 022113114006        6       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 2      Maine 023113114001        1       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 3      Maine 023113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 4      Maine 023113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 5   Maryland 024113114001        1       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 6   Maryland 024113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 7   Maryland 024113114003        3       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 8   Maryland 024113114004        4       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 9   Maryland 024113114005        5       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 10  Maryland 024113114006        6       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
##     LAW NOTE BESTDEC                  FINALNOTE RNOTE
## 1  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 2  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 3  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 4  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 5  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 6  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 7  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 8  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 9  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 10 &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
##                    LASTCHANGE FROMCOUNTY year       area
## 1  2016-05-29 16:44:10.857626          F 2018 District 6
## 2  2016-05-29 16:44:10.857626          F 2018 District 1
## 3  2016-05-29 16:44:10.857626          F 2018 District 2
## 4  2016-05-29 16:44:10.857626          F 2018 District 2
## 5  2016-05-29 16:44:10.857626          F 2018 District 1
## 6  2016-05-29 16:44:10.857626          F 2018 District 2
## 7  2016-05-29 16:44:10.857626          F 2018 District 3
## 8  2016-05-29 16:44:10.857626          F 2018 District 4
## 9  2016-05-29 16:44:10.857626          F 2018 District 5
## 10 2016-05-29 16:44:10.857626          F 2018 District 6
##    dem_votes_major_percent ...1 state_dists    preds preds_high preds_low
## 1                    22.80  179        2206 21.34606  -11.20916  53.90129
## 2                    64.41  180        2301 65.49917   63.06279  67.93554
## 3                    49.59  181        2302 52.13665   53.64648  50.62681
## 4                    50.62  181        2302 52.13665   53.64648  50.62681
## 5                    38.84  182        2401 33.19491   30.73137  35.65844
## 6                    68.25  183        2402 65.58401   66.22555  64.94246
## 7                    70.97  184        2403 65.34067   66.60534  64.07600
## 8                    79.72  185        2404 75.39883   76.94046  73.85721
## 9                    72.19  186        2405 68.37075   69.74832  66.99319
## 10                   60.82  187        2406 55.56901   56.81198  54.32604
##                          geometry
## 1  MULTIPOLYGON (((785086.2 -1...
## 2  MULTIPOLYGON (((2267100 278...
## 3  MULTIPOLYGON (((2201125 435...
## 4  MULTIPOLYGON (((2201125 435...
## 5  MULTIPOLYGON (((1914812 -33...
## 6  MULTIPOLYGON (((1964892 -37...
## 7  MULTIPOLYGON (((1938359 -36...
## 8  MULTIPOLYGON (((1963456 -41...
## 9  MULTIPOLYGON (((1965332 -41...
## 10 MULTIPOLYGON (((1745420 -41...</code></pre>
<pre><code>## Simple feature collection with 435 features and 21 fields (with 1 geometry empty)
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -2031905 ymin: -2116976 xmax: 2516388 ymax: 732376
## CRS:           +proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +ellps=sphere +units=m +no_defs
## First 10 features:
##    STATENAME           ID DISTRICT STARTCONG ENDCONG DISTRICTSI COUNTY PAGE
## 1  Louisiana 022113114006        6       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 2      Maine 023113114001        1       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 3      Maine 023113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 4      Maine 023113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 5   Maryland 024113114001        1       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 6   Maryland 024113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 7   Maryland 024113114003        3       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 8   Maryland 024113114004        4       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 9   Maryland 024113114005        5       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 10  Maryland 024113114006        6       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
##     LAW NOTE BESTDEC                  FINALNOTE RNOTE
## 1  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 2  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 3  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 4  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 5  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 6  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 7  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 8  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 9  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 10 &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
##                    LASTCHANGE FROMCOUNTY year       area
## 1  2016-05-29 16:44:10.857626          F 2018 District 6
## 2  2016-05-29 16:44:10.857626          F 2018 District 1
## 3  2016-05-29 16:44:10.857626          F 2018 District 2
## 4  2016-05-29 16:44:10.857626          F 2018 District 2
## 5  2016-05-29 16:44:10.857626          F 2018 District 1
## 6  2016-05-29 16:44:10.857626          F 2018 District 2
## 7  2016-05-29 16:44:10.857626          F 2018 District 3
## 8  2016-05-29 16:44:10.857626          F 2018 District 4
## 9  2016-05-29 16:44:10.857626          F 2018 District 5
## 10 2016-05-29 16:44:10.857626          F 2018 District 6
##    dem_votes_major_percent ...1 state_dists    preds
## 1                    22.80  179        2206 19.01665
## 2                    64.41  180        2301 59.07367
## 3                    49.59  181        2302 59.19794
## 4                    50.62  181        2302 59.19794
## 5                    38.84  182        2401 35.89440
## 6                    68.25  183        2402 63.15065
## 7                    70.97  184        2403 73.34389
## 8                    79.72  185        2404 72.76625
## 9                    72.19  186        2405 69.61717
## 10                   60.82  187        2406 64.96749
##                          geometry
## 1  MULTIPOLYGON (((785086.2 -1...
## 2  MULTIPOLYGON (((2267100 278...
## 3  MULTIPOLYGON (((2201125 435...
## 4  MULTIPOLYGON (((2201125 435...
## 5  MULTIPOLYGON (((1914812 -33...
## 6  MULTIPOLYGON (((1964892 -37...
## 7  MULTIPOLYGON (((1938359 -36...
## 8  MULTIPOLYGON (((1963456 -41...
## 9  MULTIPOLYGON (((1965332 -41...
## 10 MULTIPOLYGON (((1745420 -41...</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre><code>## Simple feature collection with 437 features and 27 fields (with 1 geometry empty)
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -2031905 ymin: -2116976 xmax: 2516388 ymax: 732376
## CRS:           +proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +ellps=sphere +units=m +no_defs
## First 10 features:
##    STATENAME           ID DISTRICT STARTCONG ENDCONG DISTRICTSI COUNTY PAGE
## 1  Louisiana 022113114006        6       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 2      Maine 023113114001        1       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 3      Maine 023113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 4      Maine 023113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 5   Maryland 024113114001        1       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 6   Maryland 024113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 7   Maryland 024113114003        3       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 8   Maryland 024113114004        4       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 9   Maryland 024113114005        5       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 10  Maryland 024113114006        6       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
##     LAW NOTE BESTDEC                  FINALNOTE RNOTE
## 1  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 2  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 3  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 4  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 5  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 6  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 7  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 8  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 9  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 10 &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
##                    LASTCHANGE FROMCOUNTY year       area
## 1  2016-05-29 16:44:10.857626          F 2018 District 6
## 2  2016-05-29 16:44:10.857626          F 2018 District 1
## 3  2016-05-29 16:44:10.857626          F 2018 District 2
## 4  2016-05-29 16:44:10.857626          F 2018 District 2
## 5  2016-05-29 16:44:10.857626          F 2018 District 1
## 6  2016-05-29 16:44:10.857626          F 2018 District 2
## 7  2016-05-29 16:44:10.857626          F 2018 District 3
## 8  2016-05-29 16:44:10.857626          F 2018 District 4
## 9  2016-05-29 16:44:10.857626          F 2018 District 5
## 10 2016-05-29 16:44:10.857626          F 2018 District 6
##    dem_votes_major_percent ...1.x state_dists.x preds.x ...1.y state_dists.y
## 1                    22.80    179          2206       0    179          2206
## 2                    64.41    180          2301       1    180          2301
## 3                    49.59    181          2302       1    181          2302
## 4                    50.62    181          2302       1    181          2302
## 5                    38.84    182          2401       0    182          2401
## 6                    68.25    183          2402       1    183          2402
## 7                    70.97    184          2403       1    184          2403
## 8                    79.72    185          2404       1    185          2404
## 9                    72.19    186          2405       1    186          2405
## 10                   60.82    187          2406       1    187          2406
##    preds.y preds_high preds_low pred.diff                       geometry
## 1        0  -11.20916  53.90129         0 MULTIPOLYGON (((785086.2 -1...
## 2        1   63.06279  67.93554         0 MULTIPOLYGON (((2267100 278...
## 3        1   53.64648  50.62681         0 MULTIPOLYGON (((2201125 435...
## 4        1   53.64648  50.62681         0 MULTIPOLYGON (((2201125 435...
## 5        0   30.73137  35.65844         0 MULTIPOLYGON (((1914812 -33...
## 6        1   66.22555  64.94246         0 MULTIPOLYGON (((1964892 -37...
## 7        1   66.60534  64.07600         0 MULTIPOLYGON (((1938359 -36...
## 8        1   76.94046  73.85721         0 MULTIPOLYGON (((1963456 -41...
## 9        1   69.74832  66.99319         0 MULTIPOLYGON (((1965332 -41...
## 10       1   56.81198  54.32604         0 MULTIPOLYGON (((1745420 -41...</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-4-2.png" width="672" />
With the incorporation of incumbency into my model, I saw 36 states flip. So turnout had an affect on my predictions. With the turnout variable, I predict that Democrats will receive 220 seats.</p>
<pre><code>## Simple feature collection with 435 features and 25 fields (with 1 geometry empty)
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -2031905 ymin: -2116976 xmax: 2516388 ymax: 732376
## CRS:           +proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +ellps=sphere +units=m +no_defs
## First 10 features:
##    STATENAME           ID DISTRICT STARTCONG ENDCONG DISTRICTSI COUNTY PAGE
## 1  Louisiana 022113114006        6       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 2      Maine 023113114001        1       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 3      Maine 023113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 4      Maine 023113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 5   Maryland 024113114001        1       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 6   Maryland 024113114002        2       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 7   Maryland 024113114003        3       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 8   Maryland 024113114004        4       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 9   Maryland 024113114005        5       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
## 10  Maryland 024113114006        6       113     114       &lt;NA&gt;   &lt;NA&gt; &lt;NA&gt;
##     LAW NOTE BESTDEC                  FINALNOTE RNOTE
## 1  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 2  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 3  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 4  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 5  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 6  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 7  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 8  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 9  &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
## 10 &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt; {&quot;From US Census website&quot;}  &lt;NA&gt;
##                    LASTCHANGE FROMCOUNTY year.x     area.x
## 1  2016-05-29 16:44:10.857626          F   2018 District 6
## 2  2016-05-29 16:44:10.857626          F   2018 District 1
## 3  2016-05-29 16:44:10.857626          F   2018 District 2
## 4  2016-05-29 16:44:10.857626          F   2018 District 2
## 5  2016-05-29 16:44:10.857626          F   2018 District 1
## 6  2016-05-29 16:44:10.857626          F   2018 District 2
## 7  2016-05-29 16:44:10.857626          F   2018 District 3
## 8  2016-05-29 16:44:10.857626          F   2018 District 4
## 9  2016-05-29 16:44:10.857626          F   2018 District 5
## 10 2016-05-29 16:44:10.857626          F   2018 District 6
##    dem_votes_major_percent.x ...1 state_dists preds year.y     area.y
## 1                      22.80  179        2206     0   2020 District 6
## 2                      64.41  180        2301     1   2020 District 1
## 3                      49.59  181        2302     1   2020 District 2
## 4                      50.62  181        2302     1   2020 District 2
## 5                      38.84  182        2401     0   2020 District 1
## 6                      68.25  183        2402     1   2020 District 2
## 7                      70.97  184        2403     1   2020 District 3
## 8                      79.72  185        2404     1   2020 District 4
## 9                      72.19  186        2405     1   2020 District 5
## 10                     60.82  187        2406     1   2020 District 6
##    dem_votes_major_percent.y pred.diff                       geometry
## 1                          0         0 MULTIPOLYGON (((785086.2 -1...
## 2                          1         0 MULTIPOLYGON (((2267100 278...
## 3                          1         0 MULTIPOLYGON (((2201125 435...
## 4                          1         0 MULTIPOLYGON (((2201125 435...
## 5                          0         0 MULTIPOLYGON (((1914812 -33...
## 6                          1         0 MULTIPOLYGON (((1964892 -37...
## 7                          1         0 MULTIPOLYGON (((1938359 -36...
## 8                          1         0 MULTIPOLYGON (((1963456 -41...
## 9                          1         0 MULTIPOLYGON (((1965332 -41...
## 10                         1         0 MULTIPOLYGON (((1745420 -41...</code></pre>
<div id="data" class="section level1">
<h1>Data</h1>
</div>
<div id="model-with-turnout" class="section level1">
<h1>Model with Turnout</h1>
<pre><code>## [1] &quot;5600&quot;</code></pre>
<pre><code>## 
## ==================================================
##                            Dependent variable:    
##                        ---------------------------
##                           DemVotesMajorPercent    
## --------------------------------------------------
## average_support                   1.347           
##                                  (1.397)          
##                                                   
## turnout                           0.089           
##                                  (0.313)          
##                                                   
## gdp_percent_difference           -0.379           
##                                  (0.323)          
##                                                   
## incumb                                            
##                                                   
##                                                   
## Constant                         -36.698          
##                                 (60.562)          
##                                                   
## --------------------------------------------------
## Observations                        5             
## R2                                0.614           
## Adjusted R2                      -0.544           
## Residual Std. Error          4.485 (df = 1)       
## F Statistic                 0.530 (df = 3; 1)     
## ==================================================
## Note:                  *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<pre><code>## [1] 221</code></pre>
<pre><code>## [1] 214</code></pre>
<pre><code>## [1] 224</code></pre>
<pre><code>## [1] 211</code></pre>
<pre><code>## [1] 215</code></pre>
<pre><code>## [1] 220</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-27-1.png" width="672" />
I then calculated how a change in the level of turnout would change the election results. I did the most extreme turnout change of 8%, since Enos and Fowler found that campaigns have the potential to effect turnout by 8 percentage points. I found that low turnout benefits Democrats, as they win the house majority with 220 seats. Then, with average turnout, Republicans take the house majority with 221 seats. Finally, with high turnout, Republicans have house majority with 224 seats.</p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-29-1.png" width="672" />
I then graphed the R2 values of the model for each state. Most of the values were close to 1, indicating that this is a decent model. This model shows the R2 for the forecast which includes all the variables. However, when I isolate R2 of turnout it is 0.089, which is not a statistically significant R2 value. Therefore, in later iterations of my model I likely will remove turnout from the model.</p>
</div>
